SELECT
    C.COLLECTOR_ID,
    (
    SELECT
        COUNT(*)
    FROM
        SALES     S
        JOIN PAINTINGS P
        ON S.PAINTING_ID = P.PAINTING_ID JOIN ARTIST A
        ON P.ARTIST_ID = A.ARTIST_ID
    WHERE
        S.COLLECTOR_ID = C.COLLECTOR_ID ) AS NUM_PAINTINGS_BOUGHT
    FROM
        COLLECTORS C;