CREATE TABLE ITEMS (
    ITEM_ID INT PRIMARY KEY,
    ITEM_NAME VARCHAR(50),
    ITEM_PRICE DECIMAL(10, 2),
    EXPIRATION_DATE DATE,
    QUANTITY_IN_HAND INT
);

SELECT
    ITEM_NAME,
    ITEM_PRICE
FROM
    ITEMS
WHERE
    QUANTITY_IN_HAND > 20;

SELECT
    ITEM_NAME
FROM
    ITEMS
WHERE
    EXPIRATION_DATE < SYSDATE;

SELECT
    ITEM_NAME
FROM
    ITEMS
ORDER BY
    ITEM_PRICE DESC OFFSET 1 ROW FETCH NEXT 1 ROW ONLY;

SELECT
    TOP 1 ITEM_NAME,
    ITEM_PRICE
FROM
    (
        SELECT
            TOP 2 ITEM_NAME,
            ITEM_PRICE
        FROM
            ITEMS
        ORDER BY
            ITEM_PRICE DESC
    )
ORDER BY
    ITEM_PRICE ASC;

ALTER TABLE ITEMS MODIFY ITEM_PRICE DECIMAL(10, 2) CHECK (ITEM_PRICE >= 0);